-- Consulta Compleja 
--Mostrar todos las ventas generadas de todas las fechas desagrupado por clientes, marcas, categorias y cantidades

SELECT  CD.CODCOM 					AS CODIGO_COMPROBANTE,
				PROD.NOMPROD 			AS NOMBRE_PRODUCTO, 
				CLI.NOMCLI 					   AS CLIENTE ,
				MC.NOMMAR  					AS NOMBRE_MARCA,
				CAT.NOMCAT 					AS NOMBRE_CATEGORIA,
				CD.CANTIDAD  				AS CANTIDAD_VENDIDA,
				CC.FECHA						AS FECHA
FROM SUPERMERCADO.COMP_DETALLE CD 
INNER JOIN SUPERMERCADO.COMP_CABECERA CC ON CD.CODCOM=CC.CODCOM
INNER JOIN SUPERMERCADO.PRODUCTOS PROD  ON     PROD.CODPROD=CD.CODPROD
INNER JOIN SUPERMERCADO.CLIENTES CLI ON CLI.CODCLI=CC.CODCLI 
INNER JOIN SUPERMERCADO.MARCAS MC ON MC.CODMAR=PROD.CODMAR
INNER JOIN SUPERMERCADO.CATEGORIAS CAT ON CAT.CODCAT=PROD.CODCAT
ORDER BY CC.FECHA DESC

-- Mostrar todos las categorias de productos mas vendidos por el personal a cargo desagregado por distrito y forma de pago correspondiente

SELECT  DIS.NOMDIS AS NOMBRE_DISTRITO, 
				CARGO.NOMCAR AS CARGO, 
				PER.NOMPER AS PERSONAL, 
				CAT.NOMCAT AS CATEGORIA, 
				FP.NOMFOR AS FORMA_PAGO,  
				CD.CANTIDAD  AS  CANTIDAD_VENDIDA
FROM SUPERMERCADO.COMP_DETALLE CD
INNER JOIN SUPERMERCADO.COMP_CABECERA 	CC 		 ON CC.CODCOM=CD.CODCOM
INNER JOIN SUPERMERCADO.LOCALES LOCAL    ON CC.CODLOC=LOCAL.CODLOC
INNER JOIN SUPERMERCADO.DISTRITOS DIS 	 	ON LOCAL.CODDIS= DIS.CODDIS
INNER JOIN SUPERMERCADO.PRODUCTOS PROD ON PROD.CODPROD=CD.CODPROD
INNER JOIN SUPERMERCADO.CATEGORIAS CAT  ON  CAT.CODCAT=PROD.CODCAT
INNER JOIN SUPERMERCADO.PERSONAL PER ON PER.CODPER=CC.CODPER
INNER JOIN SUPERMERCADO.CARGOS CARGO ON CARGO.CODCAR=PER.CODCAR
INNER JOIN SUPERMERCADO.FORMAS_PAGO  FP ON CC.CODFOR=FP.CODFOR
ORDER BY 6 DESC;