CREATE OR REPLACE PROCEDURE PR_CON_AHORROS
(
  P_SUCURSAL IN EUREKA.CUENTA.CHR_SUCUCODIGO%TYPE,
  P_AHORROS_SOLES OUT NUMBER,
  P_AHORROS_DOLARES OUT NUMBER,
  P_MENSAJE OUT VARCHAR2
)
IS
  V_CONT  NUMBER(5);
  V_FLAT NUMBER(5);
  V_CODMONEDA VARCHAR2(2);
BEGIN
    V_FLAT := 1;
    -- VALIDAR
    SELECT COUNT(CHR_SUCUCODIGO) INTO V_CONT 
    FROM EUREKA.CUENTA
    WHERE  CHR_SUCUCODIGO = P_SUCURSAL;
    
    IF V_CONT = 0 THEN
      V_FLAT := 0;
      P_MENSAJE := 'NO EXISTE LA SUCURSAL';
      RETURN;
    END IF;
  
    IF V_FLAT <> 0 THEN
    SELECT SUM(DEC_CUENSALDO)
    INTO P_AHORROS_SOLES
    FROM EUREKA.CUENTA
    WHERE CHR_MONECODIGO = '01' AND CHR_SUCUCODIGO = P_SUCURSAL;
    
    
    SELECT SUM(DEC_CUENSALDO)
    INTO P_AHORROS_DOLARES
    FROM EUREKA.CUENTA
    WHERE CHR_MONECODIGO = '02' AND CHR_SUCUCODIGO = P_SUCURSAL;
    
    P_MENSAJE := 'SUCURSAL EXISTE';
    END IF;    
END;
