/*******
RAMOS CUEVA, CESAR
SARAVIA
JARA
*******/

CREATE OR REPLACE PROCEDURE PR_CON_AHORROS
( 
  P_SUCURSAL  		IN VARCHAR2,
  P_AHORRO_SOLES  	OUT NUMBER,
  P_AHORRO_DOLARES 	OUT NUMBER,
  P_MENSAJE  		OUT VARCHAR2
)
IS
  V_CONT  NUMBER(5);
BEGIN
  -- VALIDAR
  SELECT COUNT(1) INTO V_CONT 
  FROM   EUREKA.CUENTA
  WHERE  CHR_SUCUCODIGO = P_SUCURSAL ;
  
  IF V_CONT < 1 THEN
    P_MENSAJE := 'NO EXISTE EL CODIGO SUCURSAL';
    RETURN;
  END IF;
  
  -- PROCESO
  
SELECT 
	 SUM(DEC_CUENSALDO)
	INTO   P_AHORRO_SOLES
  FROM   EUREKA.CUENTA
  WHERE  CHR_SUCUCODIGO = P_SUCURSAL AND CHR_MONECODIGO = '01'
  GROUP BY CHR_SUCUCODIGO;

SELECT 
	SUM(DEC_CUENSALDO)
	INTO   P_AHORRO_DOLARES
  FROM   EUREKA.CUENTA
  WHERE  CHR_SUCUCODIGO = P_SUCURSAL AND CHR_MONECODIGO = '02'
  GROUP BY CHR_SUCUCODIGO;
    
  
  P_MENSAJE := 'OK';
  
END;
/


BEGIN
	EUREKA.PR_CON_AHORROS ('002', :p_ahorro_soles$NUMBER, :p_ahorro_dolares$NUMBER, :p_mensaje$VARCHAR2);
END;