--Caso: Gestión de cobranza en un banco
--Curso: PLSQL Oracle 19-02
--Profesor: Ing. Eric Gustavo Coronel Castillo
--Integrantes: Mónica Huertas, Oscar Zúñiga, Hernán Cama

-- =============================================
-- CREACIÓN DE USUARIO
-- =============================================

DECLARE
	N INT;
	COMMAND VARCHAR2(200);
BEGIN
	COMMAND := 'DROP USER COBRANZA CASCADE';
	SELECT COUNT(*) INTO N
	FROM DBA_USERS
	WHERE USERNAME = 'COBRANZA';
	IF ( N = 1 ) THEN
		EXECUTE IMMEDIATE COMMAND;
	END IF;
END;
/


CREATE USER COBRANZA IDENTIFIED BY admin;
GRANT CONNECT, RESOURCE TO COBRANZA;
ALTER USER COBRANZA
QUOTA UNLIMITED ON USERS;
GRANT CREATE VIEW TO COBRANZA;

connect COBRANZA/admin;


-- =============================================
-- CREACIÓN DE LOS OBJETOS DE LA BASE DE DATOS
-- =============================================

CREATE TABLE COBRANZA.GESTOR (
id_gestor VARCHAR(2) NOT NULL,
tipo_documento VARCHAR(4) NOT NULL,
nro_documento VARCHAR(20) NOT NULL,
nombres VARCHAR(100) NOT NULL,
apellidos VARCHAR(100) NOT NULL,
sexo VARCHAR(1) NOT NULL,
fecha_nacimiento DATE NULL,
celular NUMBER(9,0) NULL,
direccion VARCHAR(200) NOT NULL,
distrito VARCHAR(200) NOT NULL,
provincia VARCHAR(50) NOT NULL,
departamento VARCHAR(50) NOT NULL,
CONSTRAINT XPKGESTOR PRIMARY KEY (id_gestor)
);

CREATE TABLE COBRANZA.CLIENTE (
id_cliente VARCHAR(2) NOT NULL,
tipo_documento VARCHAR(4) NOT NULL,
nro_documento VARCHAR(20) NOT NULL,
nombres VARCHAR(100) NOT NULL,
apellidos VARCHAR(100) NOT NULL,
sexo VARCHAR(1) NOT NULL,
fecha_nacimiento DATE NULL,
celular NUMBER(9,0) NULL,
direccion VARCHAR(200) NOT NULL,
distrito VARCHAR(200) NOT NULL,
provincia VARCHAR(50) NOT NULL,
departamento VARCHAR(50) NOT NULL,
CONSTRAINT XPKCLIENTE PRIMARY KEY (id_cliente)
);

CREATE TABLE COBRANZA.MONEDA (
id_moneda VARCHAR(2) NOT NULL,
descripcion varchar(10) NOT NULL,
CONSTRAINT XPKMONEDA PRIMARY KEY (id_moneda)
);

CREATE TABLE COBRANZA.CUENTA (
id_cuenta VARCHAR(2) NOT NULL,
id_cliente VARCHAR(2) NOT NULL,
id_moneda VARCHAR(2) NOT NULL,
monto_desembolso NUMBER(6,0) NOT NULL,
n_cuotas NUMBER(2,0) NOT NULL,
fecha_apertura DATE NOT NULL,
CONSTRAINT XPKCUENTA PRIMARY KEY (id_cuenta),
CONSTRAINT FK_CUENTA_CLIENTE FOREIGN KEY (id_cliente) REFERENCES COBRANZA.CLIENTE, 
CONSTRAINT FK_CUENTA_MONEDA FOREIGN KEY (id_moneda) REFERENCES COBRANZA.MONEDA
);

CREATE TABLE COBRANZA.CRONOGRAMA (
id_cronograma NUMBER(10,0) NOT NULL,
id_cuenta VARCHAR(2) NOT NULL,
nro_cuota NUMBER(2,0) NOT NULL,
fecha_vencimiento DATE NOT NULL,
capital NUMBER(6,0) NOT NULL,
interes NUMBER(6,0) NOT NULL,
CONSTRAINT XPKCRONOGRAMA PRIMARY KEY (id_cronograma),
CONSTRAINT FK_CRONOGRAMA_CUENTA FOREIGN KEY (id_cuenta) REFERENCES COBRANZA.CUENTA 
);

CREATE TABLE COBRANZA.DESCUENTO (
id_descuento VARCHAR(2) NOT NULL,
dscto_porcentaje NUMBER(2,1) NOT NULL,
descripcion VARCHAR(100) NOT NULL,
CONSTRAINT XPKDESCUENTO PRIMARY KEY (id_descuento)
);

CREATE TABLE COBRANZA.PAGO (
id_pago NUMBER(10,0) NOT NULL,
fecha_pago DATE NOT NULL,
id_cuenta VARCHAR(2) NOT NULL,
monto_pago NUMBER(6,0) NOT NULL,
id_descuento VARCHAR(2) NOT NULL,
CONSTRAINT XPKPAGO PRIMARY KEY (id_pago),
CONSTRAINT FK_PAGO_CUENTA FOREIGN KEY (id_cuenta) REFERENCES COBRANZA.CUENTA,
CONSTRAINT FK_PAGO_DESCUENTO FOREIGN KEY (id_descuento) REFERENCES COBRANZA.DESCUENTO
);

CREATE TABLE COBRANZA.GESTION_COBRANZA (
id_gestion NUMBER(5,0) NOT NULL,
fecha_gestion DATE NOT NULL,
id_gestor VARCHAR(2) NOT NULL,
id_cliente VARCHAR(2) NOT NULL,
tipo_contacto VARCHAR(20) NOT NULL,
promesa_pago VARCHAR(2) NULL,
fecha_promesa_pago DATE NULL,
CONSTRAINT XPKGESTION_COBRANZA PRIMARY KEY (id_gestion),
CONSTRAINT FK_GESTION_COBRANZA_GESTOR FOREIGN KEY (id_gestor) REFERENCES COBRANZA.GESTOR,
CONSTRAINT FK_GESTION_COBRANZA_CLIENTE FOREIGN KEY (id_cliente) REFERENCES COBRANZA.CLIENTE
);


-- =============================================
-- FIN DE LA CREACION DEL ESQUEMA
-- =============================================
