--CREACION DE USUARIO || TABLESPACE

DECLARE
    N INT;
    COMMAND VARCHAR2(200);
BEGIN
    COMMAND := 'DROP USER VENTAS CASCADE';
    SELECT COUNT(*) INTO N
    FROM DBA_USERS
    WHERE USERNAME = 'VENTAS';
    IF ( N = 1 ) THEN
        EXECUTE IMMEDIATE COMMAND;
    END IF;
END;
/

CREATE USER VENTAS IDENTIFIED BY admin;
GRANT CONNECT, RESOURCE TO VENTAS;

GRANT CREATE VIEW TO VENTAS;
GRANT CREATE TABLE TO VENTAS;

-- =========================================
-- 01: CREAR EL TABLESPACE
-- =========================================

CREATE TABLESPACE TBS_VENTAS
DATAFILE 'E:\app\TS\DF_VENTAS.DBF'
SIZE 1000M;

ALTER USER VENTAS  
    DEFAULT TABLESPACE TBS_VENTAS 
    QUOTA UNLIMITED ON TBS_VENTAS;

COMMIT;

