-- =============================================
-- CONECTARSE A LA APLICACIÓN
-- =============================================
CONNECT VENTAS/admin

CREATE TABLE EMPRESA
( IDEMPRESA number NOT NULL,
  RAZON_SOCIAL varchar2(50) NOT NULL,
  NUMERO_RUC NUMBER NOT NULL,
  DIRECCION varchar2(150),
  CONSTRAINT EMPRESA_PK PRIMARY KEY (IDEMPRESA)
);
---CREATE SEQUENCE IDEMPRESA START WITH 1;

CREATE TABLE TIPODOCUMENTO
( IDTIPODOCUMENTO NUMBER NOT NULL,
  DESCRIPCION  VARCHAR2(50) NOT NULL,
  ESTADO NUMBER,
  CONSTRAINT TIPODOCUMENTO_PK PRIMARY KEY (IDTIPODOCUMENTO)
);
---CREATE SEQUENCE IDTIPODOCUMENTO START WITH 1;

CREATE TABLE CLIENTE
( IDCLIENTE NUMBER NOT NULL,
  IDTIPODOCUMENTO  NUMBER NOT NULL,
  NRODOCUMENTO  VARCHAR2(12) NOT NULL,
  NOMBRE  VARCHAR2(50) NOT NULL,
  APELLIDO_PATERNO VARCHAR2(50) ,
  APELLIDO_MATERNO VARCHAR2(50) ,
  RAZON_SOCIAL VARCHAR2(12) ,
  DIRECCION VARCHAR2(150),
  FECHA_NACIMIENTO DATE,
  ESTADO NUMBER,
  CONSTRAINT CLIENTE_PK PRIMARY KEY (IDCLIENTE)
);
--CREATE SEQUENCE IDCLIENTE START WITH 1;

CREATE TABLE PRODUCTO
( IDPRODUCTO NUMBER NOT NULL,
  NOMBRE VARCHAR2(250) NOT NULL,
  DESCRIPCION  VARCHAR2(500),
  PRECIO DECIMAL(18,2),
  CONSTRAINT PRODUCTO_PK PRIMARY KEY (IDPRODUCTO)
);
--CREATE SEQUENCE IDPRODUCTO START WITH 1;

CREATE TABLE VENTA
( IDVENTA NUMBER NOT NULL,
  IDEMPRESA NUMBER NOT NULL,
  IDCLIENTE NUMBER NOT NULL,
  SERIE  VARCHAR2(30),
  NUMERO VARCHAR2(20),
  MONTO_BRUTO DECIMAL(18,2),
  MONTO_IGV DECIMAL(18,2),
  MONTO_TOTAL DECIMAL(18,2),  
  FECHA_EMISION DATE,
  CONSTRAINT VENTA_PK PRIMARY KEY (IDVENTA)
);
--CREATE SEQUENCE IDVENTA START WITH 1;

--DROP SEQUENCE IDVENTA; 

CREATE TABLE DETALLEVENTA
( IDDETALLEVENTA NUMBER NOT NULL,
( IDVENTA NUMBER NOT NULL,
  IDPRODUCTO NUMBER NOT NULL,
  PRECIO DECIMAL(18,2),
  CANTIDAD DECIMAL(18,2),
  IGV DECIMAL(18,2),  
  CONSTRAINT DETALLEVENTA_PK PRIMARY KEY (IDDETALLEVENTA)
);
--CREATE SEQUENCE IDDETALLEVENTA START WITH 1;

-----CONSTRAINT FOREIGN KEY

--CLIENTE
ALTER TABLE CLIENTE ADD FOREIGN KEY (IDTIPODOCUMENTO) REFERENCES TIPODOCUMENTO(IDTIPODOCUMENTO);

--VENTA
ALTER TABLE VENTA ADD FOREIGN KEY (IDEMPRESA) REFERENCES EMPRESA(IDEMPRESA);
ALTER TABLE VENTA ADD FOREIGN KEY (IDCLIENTE) REFERENCES CLIENTE(IDCLIENTE);

--DETALLE VENTA
ALTER TABLE DETALLEVENTA ADD FOREIGN KEY (IDVENTA) REFERENCES VENTA(IDVENTA);
ALTER TABLE DETALLEVENTA ADD FOREIGN KEY (IDPRODUCTO) REFERENCES PRODUCTO(IDPRODUCTO);

COMMIT;