-- =============================================
-- CONECTARSE A LA APLICACIÓN
-- =============================================
CONNECT VENTAS/admin

--SELECT * FROM VENTAS.EMPRESA;

INSERT INTO EMPRESA(IDEMPRESA,RAZON_SOCIAL,NUMERO_RUC,DIRECCION)VALUES(1,'Tambo','20516045397','AV. San Juan Alto');
INSERT INTO EMPRESA(IDEMPRESA,RAZON_SOCIAL,NUMERO_RUC,DIRECCION)VALUES(2,'Oxo','20516445337','AV. San Juan Alto 2');

COMMIT;