--REPORTES

CREATE OR REPLACE PROCEDURE VENTAS.PRC_LISTADO_CLIENTES_COMPRAS
(
    RC OUT SYS_REFCURSOR
)
IS
BEGIN    
    OPEN RC FOR
    SELECT C.IDCLIENTE,C.NOMBRE,C.APELLIDO_PATERNO,C.APELLIDO_MATERNO, COUNT(*) 
    FROM VENTAS.CLIENTE C
    INNER JOIN VENTAS.VENTA V ON C.IDCLIENTE = V.IDCLIENTE
    GROUP BY C.IDCLIENTE,C.NOMBRE,C.APELLIDO_PATERNO,C.APELLIDO_MATERNO
    HAVING COUNT(*)>0;
END;


CREATE OR REPLACE PROCEDURE VENTAS.PRC_BUSQUEDAVENTAS
(
    FECHA_INICIO DATE,
    FECHA_FIN DATE,
    RC OUT SYS_REFCURSOR
)
IS
BEGIN    
    OPEN RC FOR    
    SELECT (C.NOMBRE || C.APELLIDO_PATERNO || C.APELLIDO_MATERNO ) NOMBRES, EM.RAZON_SOCIAL,V.SERIE,V.NUMERO,V.MONTO_BRUTO,V.MONTO_IGV, V.MONTO_TOTAL  
    FROM VENTAS.VENTA V
    INNER JOIN VENTAS.CLIENTE C ON V.IDCLIENTE = C.IDCLIENTE
    INNER JOIN VENTAS.EMPRESA EM ON V.IDEMPRESA=EM.IDEMPRESA
    WHERE  FECHA_EMISION BETWEEN VENTAS.PRC_BUSQUEDAVENTAS.FECHA_INICIO AND VENTAS.PRC_BUSQUEDAVENTAS.FECHA_FIN;
END;
