CREATE OR REPLACE PROCEDURE VENTAS.PRC_INSERTARCLIENTE
(
    IDTIPODOCUMENTO  NUMBER,
    NUMERODOCU          VARCHAR,
    NOMBRE                   VARCHAR,
    AP_PATERNO            VARCHAR,
    AP_MATERNO            VARCHAR,
    RAZONSOCIAL            VARCHAR,
    DIRECCION                VARCHAR,
    FECHANACIMIENTO    DATE,
    CODCLIENTE     OUT     INT 
)
IS
CANTIDAD NUMBER;
CANTIDADMAX NUMBER;
BEGIN
    SELECT COUNT(*) INTO CANTIDAD 
    FROM VENTAS.CLIENTE 
    WHERE IDTIPODOCUMENTO = PRC_INSERTARCLIENTE.IDTIPODOCUMENTO
    AND NRODOCUMENTO = PRC_INSERTARCLIENTE.NUMERODOCU;
    
    IF(CANTIDAD = 0 )   THEN
            SELECT MAX(IDCLIENTE) INTO CANTIDADMAX FROM CLIENTE;
    
            INSERT INTO VENTAS.CLIENTE(IDCLIENTE,IDTIPODOCUMENTO,NRODOCUMENTO,NOMBRE,APELLIDO_PATERNO,APELLIDO_MATERNO,RAZON_SOCIAL,DIRECCION,FECHA_NACIMIENTO,ESTADO)
            VALUES((CANTIDADMAX+1), PRC_INSERTARCLIENTE.IDTIPODOCUMENTO,PRC_INSERTARCLIENTE.NUMERODOCU, PRC_INSERTARCLIENTE.NOMBRE, PRC_INSERTARCLIENTE.AP_PATERNO,
            PRC_INSERTARCLIENTE.AP_MATERNO ,PRC_INSERTARCLIENTE.RAZONSOCIAL,PRC_INSERTARCLIENTE.DIRECCION,PRC_INSERTARCLIENTE.FECHANACIMIENTO,1);
    
    END IF;
    
    SELECT IDCLIENTE  INTO PRC_INSERTARCLIENTE.CODCLIENTE 
        FROM VENTAS.CLIENTE 
        WHERE IDTIPODOCUMENTO = PRC_INSERTARCLIENTE.IDTIPODOCUMENTO
        AND NRODOCUMENTO = PRC_INSERTARCLIENTE.NUMERODOCU;
    
END;

