-- =============================================
-- CONECTARSE A LA APLICACIÓN
-- =============================================
CONNECT VENTAS/admin

DROP TABLE VENTAS.DETALLEVENTA;
DROP TABLE VENTAS.VENTA;
DROP TABLE VENTAS.EMPRESA;
DROP TABLE VENTAS.CLIENTE;
DROP TABLE VENTAS.TIPODOCUMENTO;
DROP TABLE VENTAS.PRODUCTO;

commit;