--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
-----------------------------------ESQUEMA SUPERMERCADO TRANSACCION DE VENTAS CABECERA Y DETALLE ------------------------------------------------------------------------
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

CREATE OR REPLACE PACKAGE SUPERMERCADO.PKG_EGCC_UTIL IS

TYPE T_ARRAY_STRING IS TABLE OF VARCHAR2(1000)INDEX BY BINARY_INTEGER;

FUNCTION SPLIT(P_DATA VARCHAR2, P_DELIMITADOR VARCHAR2 ) RETURN T_ARRAY_STRING;
 
FUNCTION IS_DATE(P_FECHA IN VARCHAR2) 
RETURN NUMBER;

END;
/

CREATE OR REPLACE PACKAGE BODY SUPERMERCADO.PKG_EGCC_UTIL IS

FUNCTION SPLIT(P_DATA VARCHAR2, P_DELIMITADOR VARCHAR2 ) RETURN T_ARRAY_STRING
IS
    I        NUMBER   := 0;
    POS      NUMBER   := 0;
    V_DATA   CLOB     := P_DATA;
    STRINGS  T_ARRAY_STRING;
BEGIN
  V_DATA := TRIM( V_DATA );
  POS := INSTR( V_DATA, P_DELIMITADOR, 1, 1 );
  WHILE ( POS != 0) LOOP
      I := I + 1;
      STRINGS(i) := SUBSTR( V_DATA, 1, POS - 1 );
      V_DATA :=  SUBSTR( V_DATA, POS + 1, LENGTH(V_DATA) );
      pos := instr(V_DATA, P_DELIMITADOR, 1, 1);
      IF POS = 0 THEN
          STRINGS( I + 1 ) := V_DATA;
      END IF;    
  END LOOP;
  IF I = 0 AND LENGTH( V_DATA ) > 0 THEN
    STRINGS( I + 1 ) := V_DATA;
  END IF;
  RETURN strings;
END SPLIT;
         

FUNCTION IS_DATE(P_FECHA IN VARCHAR2) 
RETURN NUMBER 
IS
    V_FECHA DATE;
BEGIN
  V_FECHA := TO_DATE(P_FECHA,'DD/MM/YYYY');
  RETURN 1;
EXCEPTION
  WHEN OTHERS THEN
    RETURN -1;
END;


END PKG_EGCC_UTIL ;
/
--PROCEDIMIENTO DE INSERT A COMP_DETALLE

CREATE OR REPLACE PROCEDURE SUPERMERCADO.PR_INSERTA_COMP_CABECERA
( P_DATOS IN VARCHAR2, P_ESTADO OUT VARCHAR2 )
AS
  V_REGISTROS SUPERMERCADO.PKG_EGCC_UTIL.T_ARRAY_STRING;
  V_CAMPOS    SUPERMERCADO.PKG_EGCC_UTIL.T_ARRAY_STRING;
BEGIN
  P_ESTADO := 'OK';
  V_REGISTROS := SUPERMERCADO.PKG_EGCC_UTIL.SPLIT(P_DATOS,'¬');
  FOR I in 1 .. V_REGISTROS.COUNT LOOP 

    V_CAMPOS := SUPERMERCADO.PKG_EGCC_UTIL.SPLIT(V_REGISTROS(I),'|');

INSERT INTO SUPERMERCADO.COMP_CABECERA(CODCOM, CODCLI, CODPER, CODLOC, CODFOR,TIPO_COM, FECHA ) 
VALUES(V_CAMPOS(1), V_CAMPOS(2), V_CAMPOS(3),V_CAMPOS(4), V_CAMPOS(5), V_CAMPOS(6), V_CAMPOS(7) );

	END LOOP;    
  COMMIT;
    
EXCEPTION
    WHEN OTHERS THEN
        P_ESTADO := SQLERRM;
        ROLLBACK;
END;

--EJECUCION 
SELECT * FROM SUPERMERCADO.COMP_CABECERA;

DECLARE
  p_mensaje VARCHAR2(100);
BEGIN
  SUPERMERCADO.PR_INSERTA_COMP_CABECERA ('CMP005|C001|P001|L001|F001|F|07/12/2015',p_mensaje);
  DBMS_OUTPUT.PUT_LINE(p_mensaje);
END;

--VERIFICANDO 

SELECT * FROM SUPERMERCADO.COMP_CABECERA;
--CMP004|C001|P001|L001|F001|F|07/12/2015
--E0023|ZAPATA|CARLOS|02/05/2000|CARLOS.ZAPATA.TIXI@GMAIL.COM|963316238|C05|103|3000|300|E0016