

set serveroutput on;

--CREAR
DECLARE
  P_TIPO_DOCUMENTO VARCHAR2(4);
  P_NRO_DOCUMENTO VARCHAR2(20);
  P_NOMBRES VARCHAR2(100);
  P_APELLIDOS VARCHAR2(100);
  P_SEXO VARCHAR2(1);
  P_FECHA_NACIMIENTO DATE;
  P_CELULAR NUMBER;
  P_DIRECCION VARCHAR2(200);
  P_DISTRITO VARCHAR2(200);
  P_PROVINCIA VARCHAR2(50);
  P_DEPARTAMENTO VARCHAR2(50);
  P_COD_RESPUESTA NUMBER;
  P_MENSAJE VARCHAR2(200);    
BEGIN
  
  P_TIPO_DOCUMENTO:='DNI';
  P_NRO_DOCUMENTO:='123456789';
  P_NOMBRES:='hernan';
  P_APELLIDOS:='cama chamorro';
  P_SEXO:='M';
  P_FECHA_NACIMIENTO:='10/11/1985';
  P_CELULAR:=925574353;
  P_DIRECCION:='av.a';
  P_DISTRITO:='Comas';
  P_PROVINCIA:='Lima';
  P_DEPARTAMENTO:='LIma';
  P_COD_RESPUESTA := NULL;
  P_MENSAJE := NULL;
  

  PACK_CLIENTE.INSERTAR_CLIENTE (  P_TIPO_DOCUMENTO => P_TIPO_DOCUMENTO,
    P_NRO_DOCUMENTO => P_NRO_DOCUMENTO,
    P_NOMBRES => P_NOMBRES,
    P_APELLIDOS => P_APELLIDOS,
    P_SEXO => P_SEXO,
    P_FECHA_NACIMIENTO => P_FECHA_NACIMIENTO,
    P_CELULAR => P_CELULAR,
    P_DIRECCION => P_DIRECCION,
    P_DISTRITO => P_DISTRITO,
    P_PROVINCIA => P_PROVINCIA,
    P_DEPARTAMENTO => P_DEPARTAMENTO,
    P_COD_RESPUESTA => P_COD_RESPUESTA,
    P_MENSAJE => P_MENSAJE) ;  
    
    
     dbms_output.put_line(P_COD_RESPUESTA || ', ' || P_MENSAJE);
END;

---ACTUALIZAR


DECLARE
  P_ID_CLIENTE VARCHAR2(2);
  P_NOMBRES VARCHAR2(100);
  P_APELLIDOS VARCHAR2(100);
  P_SEXO VARCHAR2(1);
  P_FECHA_NACIMIENTO DATE;
  P_CELULAR NUMBER;
  P_DIRECCION VARCHAR2(200);
  P_DISTRITO VARCHAR2(200);
  P_PROVINCIA VARCHAR2(50);
  P_DEPARTAMENTO VARCHAR2(50);
  P_COD_RESPUESTA NUMBER;
  P_MENSAJE VARCHAR2(200);    
BEGIN


  P_ID_CLIENTE := 16;
  P_NOMBRES:='hernanN';
  P_APELLIDOS:='cama chamorroO';
  P_SEXO:='f';
  P_FECHA_NACIMIENTO:='10/11/1986';
  P_CELULAR:=925574355;
  P_DIRECCION:='av.aA';
  P_DISTRITO:='ComasS';
  P_PROVINCIA:='LimaA';
  P_DEPARTAMENTO:='LImaA';
  P_COD_RESPUESTA := NULL;
  P_MENSAJE := NULL;
  

  PACK_CLIENTE.MODIFICAR_CLIENTE (  P_ID_CLIENTE => P_ID_CLIENTE,
    P_NOMBRES => P_NOMBRES,
    P_APELLIDOS => P_APELLIDOS,
    P_SEXO => P_SEXO,
    P_FECHA_NACIMIENTO => P_FECHA_NACIMIENTO,
    P_CELULAR => P_CELULAR,
    P_DIRECCION => P_DIRECCION,
    P_DISTRITO => P_DISTRITO,
    P_PROVINCIA => P_PROVINCIA,
    P_DEPARTAMENTO => P_DEPARTAMENTO,
    P_COD_RESPUESTA => P_COD_RESPUESTA,
    P_MENSAJE => P_MENSAJE) ;  
    
     dbms_output.put_line(P_COD_RESPUESTA || ', ' || P_MENSAJE);
END;


--ELIMINAR



DECLARE
  P_ID_CLIENTE VARCHAR2(2);
  P_COD_RESPUESTA NUMBER;
  P_MENSAJE VARCHAR2(200);    
BEGIN
  P_ID_CLIENTE := 16;
  P_COD_RESPUESTA := NULL;
  P_MENSAJE := NULL;

  PACK_CLIENTE.ELIMINAR_CLIENTE (  P_ID_CLIENTE => P_ID_CLIENTE,
P_COD_RESPUESTA => P_COD_RESPUESTA,
P_MENSAJE => P_MENSAJE) ;  

 dbms_output.put_line(P_COD_RESPUESTA || ', ' || P_MENSAJE);
END;

--LEER SOLO REGISTRO

DECLARE
  P_ID_CLIENTE VARCHAR2(2);
  P_CURSOR SYS_REFCURSOR ;
  P_COD_RESPUESTA NUMBER;
  P_MENSAJE VARCHAR2(200);    
  reg CLIENTE%rowtype;
BEGIN
  P_ID_CLIENTE := 15;
  --P_CURSOR := NULL;
  P_COD_RESPUESTA := NULL;
  P_MENSAJE := NULL;

  PACK_CLIENTE.OBTENER_CLIENTE_ID (  P_ID_CLIENTE ,
P_CURSOR ,
P_COD_RESPUESTA ,
P_MENSAJE ) ;  

  LOOP
     if P_CURSOR%isopen then
          FETCH P_CURSOR INTO reg;
          EXIT WHEN P_CURSOR%NOTFOUND;
          -- Mostrar fila
          dbms_output.put_line(reg.NOMBRES || ', ' || reg.APELLIDOS);
           close P_CURSOR;
           
      ELSE
        EXIT;
      end if;
    
    -- Leer fila
 
  END LOOP;
   dbms_output.put_line(P_COD_RESPUESTA || ', ' || P_MENSAJE);
END;
--LEER VARIOS REGISTROS

DECLARE
  P_ID_CLIENTE VARCHAR2(2);
  P_TIPO_DOCUMENTO VARCHAR2(4);
  P_NRO_DOCUMENTO VARCHAR2(20);
  P_CURSOR SYS_REFCURSOR;
  P_COD_RESPUESTA NUMBER;
  P_MENSAJE VARCHAR2(200);    
  reg CLIENTE%rowtype;
  
BEGIN
  P_ID_CLIENTE := '0';
  P_TIPO_DOCUMENTO := 'D';
  P_NRO_DOCUMENTO := '0';
  P_CURSOR := NULL;
  P_COD_RESPUESTA := NULL;
  P_MENSAJE := NULL;

  PACK_CLIENTE.OBTENER_CLIENTES (  P_ID_CLIENTE => P_ID_CLIENTE,
P_TIPO_DOCUMENTO => P_TIPO_DOCUMENTO,
P_NRO_DOCUMENTO => P_NRO_DOCUMENTO,
P_CURSOR => P_CURSOR,
P_COD_RESPUESTA => P_COD_RESPUESTA,
P_MENSAJE => P_MENSAJE) ;  

  LOOP
     if P_CURSOR%isopen then
          FETCH P_CURSOR INTO reg;
          EXIT WHEN P_CURSOR%NOTFOUND;
          -- Mostrar fila
          dbms_output.put_line(reg.ID_CLIENTE || ', ' || reg.NOMBRES || ', ' || reg.APELLIDOS);
           --close P_CURSOR;
           
      ELSE
        EXIT;
      end if;
    
    -- Leer fila
 
  END LOOP;


  dbms_output.put_line(P_COD_RESPUESTA || ', ' || P_MENSAJE);
END;






