DECLARE
	N INT;
	COMMAND VARCHAR2(200);
BEGIN
	COMMAND := 'DROP USER HOTEL CASCADE';
	SELECT COUNT(*) INTO N
	FROM DBA_USERS
	WHERE USERNAME = 'HOTEL';
	IF ( N = 1 ) THEN
		EXECUTE IMMEDIATE COMMAND;
	END IF;
END;
/

CREATE USER HOTEL IDENTIFIED BY admin;

GRANT CONNECT, RESOURCE TO HOTEL;

ALTER USER HOTEL
QUOTA UNLIMITED ON USERS;

GRANT CREATE VIEW TO HOTEL;


-- =============================================
-- CONECTARSE A LA APLICACIÓN
-- =============================================

CONNECT HOTEL/admin