
CREATE OR REPLACE PROCEDURE HOTEL.RESERVAR_HABITACION
( 
  P_CODIGOCLI   IN  NUMBER,
  P_CODIGOHAB	IN  NUMBER,
  P_FECHAINICIO IN DATE,
  P_FECHAFIN IN DATE,
  P_PROMOCION IN NUMBER,
  P_MENSAJE  OUT VARCHAR2
)
IS
  V_CONT  NUMBER(5);
  ID_RETURN number;
  V_PRECIO NUMBER;
  V_DESCUENTO NUMBER;
  V_HABITACION NUMBER;
  V_PTOTAL NUMBER; 
BEGIN
  -- VALIDAR
  SELECT COUNT(1) INTO V_CONT 
  FROM   HOTEL.HABITACION 
  WHERE ID=P_CODIGOHAB
  AND ESTADO=0;
  
  IF V_CONT = 1 THEN
    P_MENSAJE := 'HABITACION NO DISPONIBLE';
    RETURN;
  END IF;
  
  -- PROCESO
  
  	--OBTENER PRECIO
  
  	SELECT THA.PRECIO INTO V_PRECIO FROM HOTEL.HABITACION HA
  	INNER JOIN HOTEL.TIPOHABITACION THA ON HA.IDTIPOHABITACION=THA.ID
  	WHERE HA.ID=P_CODIGOHAB;
  	
  	--OBTENER DESCUENTO
  	
  	SELECT DESCUENTO INTO V_DESCUENTO FROM HOTEL.PROMOCION WHERE ID=P_PROMOCION;
  	
  	--TRANSACCION HABITACION
  	
  	SELECT ID INTO V_HABITACION FROM HOTEL.HABITACION WHERE ID=P_CODIGOHAB FOR UPDATE;
  
  	
  	IF V_DESCUENTO IS NOT NULL THEN
  		V_PTOTAL := V_PRECIO - (V_PRECIO*V_DESCUENTO/100);
  	ELSE
  		V_PTOTAL := V_PRECIO;
  	END IF;
  	
  	
  	
	INSERT INTO HOTEL.RESERVA(FECHA,ESTADO,IDCLIENTE,FECHAINCIO,FECHAFIN,IDPROMOCION,TOTALDESCUENTO,TOTALPRECIO)
	 VALUES(SYSDATE,1,P_CODIGOCLI,P_FECHAINICIO,P_FECHAFIN,P_PROMOCION,V_DESCUENTO,V_PTOTAL) 
	 RETURNING ID into ID_RETURN;
	 
	INSERT INTO HOTEL.DETALLERESERVA(IDRESERVA,IDHABITACION,SUBTOTALDESCUENTO,SUBTOTALPRECIO)
	VALUES(ID_RETURN,V_HABITACION,V_DESCUENTO,V_PTOTAL);
	
	UPDATE HOTEL.HABITACION SET ESTADO=0 WHERE ID=V_HABITACION;
	P_MENSAJE := 'RESERVA REGISTRADA';
    COMMIT; 
EXCEPTION
  
   WHEN OTHERS THEN
	ROLLBACK;
        DBMS_OUTPUT.put_line(SQLERRM);
   
  
END;
/


DECLARE
  P_CODIGOCLI	NUMBER;
  P_CODIGOHAB	NUMBER;
  P_FECHAINICIO DATE;
  P_FECHAFIN 	DATE;
  P_PROMOCION 	NUMBER;
  P_MENSAJE  	VARCHAR2(45);
BEGIN
  -- DATOS
  P_CODIGOCLI	:=1;
  P_CODIGOHAB	:=4;
  P_FECHAINICIO :=TO_DATE('2018-03-24','yyyy-mm-dd');
  P_FECHAFIN 	:=TO_DATE('2018-03-25','yyyy-mm-dd');
  P_PROMOCION 	:=1;
  -- PROCESO
  HOTEL.RESERVAR_HABITACION(P_CODIGOCLI, P_CODIGOHAB, P_FECHAINICIO,P_FECHAFIN,P_PROMOCION,P_MENSAJE);
  -- REPORTE
  DBMS_OUTPUT.PUT_LINE('ESTADO: ' || P_MENSAJE );
END;

SELECT * FROM RESERVA;
SELECT * FROM DETALLERESERVA;