CREATE OR REPLACE FUNCTION SCOTT.FACTORIAL
(P_NUM1 NUMBER)
RETURN NUMBER
IS
V_FACT NUMBER;
BEGIN
	 V_FACT:=1;
	 FOR V_CONT IN 1 .. P_NUM1 LOOP
	 	V_FACT := V_FACT * V_CONT;
	 END LOOP;
	 RETURN V_FACT;
END;