

CREATE OR REPLACE PACKAGE RECURSOS.PKG_CRUD_EMPLEADOS AS

PROCEDURE GET_EMPS(
  P_APELLIDO  IN  VARCHAR2,
  P_NOMBRE    IN  VARCHAR2,
  P_DPTO      IN  NUMBER,
  P_CARGO     IN  VARCHAR2,
  P_CURSOR    OUT NOCOPY SYS_REFCURSOR
);


END PKG_CRUD_EMPLEADOS;
/


CREATE OR REPLACE PACKAGE BODY RECURSOS.PKG_CRUD_EMPLEADOS AS

PROCEDURE GET_EMPS(
  P_APELLIDO  IN  VARCHAR2,
  P_NOMBRE    IN  VARCHAR2,
  P_DPTO      IN  NUMBER,
  P_CARGO     IN  VARCHAR2,
  P_CURSOR    OUT NOCOPY SYS_REFCURSOR
)
AS
  V_APELLIDO  VARCHAR2(100);
  V_NOMBRE    VARCHAR2(100);
BEGIN

  -- Preparando Variables
  V_APELLIDO := '%' || P_APELLIDO || '%';
  V_NOMBRE   := '%' || P_NOMBRE   || '%';
  
  -- Verión SQL Server
  /*
  OPEN P_CURSOR FOR
  SELECT * FROM RECURSOS.EMPLEADO
  WHERE APELLIDO LIKE CASE WHEN P_APELLIDO IS NULL THEN APELLIDO ELSE V_APELLIDO END
  AND   NOMBRE   LIKE CASE WHEN P_NOMBRE   IS NULL THEN NOMBRE   ELSE V_NOMBRE   END
  AND   IDDEPARTAMENTO = CASE WHEN P_DPTO  IS NULL THEN IDDEPARTAMENTO ELSE P_DPTO  END
  AND   IDCARGO        = CASE WHEN P_CARGO IS NULL THEN IDCARGO        ELSE P_CARGO END;
  */
  
  -- Versión ORACLE
  OPEN P_CURSOR FOR
  SELECT * FROM RECURSOS.EMPLEADO
  WHERE APELLIDO       LIKE NVL2(P_APELLIDO,V_APELLIDO,APELLIDO) 
  AND   NOMBRE         LIKE NVL2(P_NOMBRE,V_NOMBRE,NOMBRE) 
  AND   IDDEPARTAMENTO =    NVL2(P_DPTO,P_DPTO,IDDEPARTAMENTO)   
  AND   IDCARGO        =    NVL2(P_CARGO,P_CARGO,IDCARGO);

END;


END PKG_CRUD_EMPLEADOS;
/

